### ISSUE TITLE
Connection

### ISSUE THREAD

**Issue by aarenclwong** [mbiselx/velarray#1]
Hey thanks for this resource, I was interested in using the M1600 and was wondering if you had good resources on how to connect the two 2 pin connectors and in general.

Thanks!

**Comment by mbiselx** [comment]
Hi! 
Unfortunately there does not seem to be any good publicly available User's Manual for the M1600. You might want to consider contacting Velodyne Lidar for a copy of the most recent version. The following is based on my experience:   
Connecting to the M1600 via a PC is not quite trivial -- the device uses 1000BASE-T1 ethernet (otherwise known as *automotive gigabit ethernet*), which has a different physical layer to the "normal" gigabit ethernet (1000BASE-TX). To interface the two, you need a *media converter*. I use the [RadMoon2 by Intrepid Control Systems](https://intrepidcs.com/products/automotive-ethernet-tools/rad-moon2-100-1000base-t1-media-converter/), but other, cheaper options might be abvailable. 
Next, you'll need to figure out what your device's IP address is. By default, it should be 192.168.1.100, but it could be literally anything. You'll also want to find out what address the device is sending to, so you can set your PC's ethernet adapter's static IP. A useful too for this can be WireShark.  (**Note**: I do not know how to change the factory-set device IP or the destination IP).
Once you have all that, you should be good to go.
